FROM php:8.2-fpm

RUN apt-get update && apt-get install -y \
        git \
        zlib1g-dev \
        libxml2-dev \
        libzip-dev \
        libpng-dev \
        nodejs npm \
    && docker-php-ext-install \
        zip \
        intl \
		mysqli \
        pdo pdo_mysql \
        gd \
    && apt-get upgrade \
    && pecl install mongodb \
    && docker-php-ext-enable mongodb
    
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

# RUN echo 'memory_limit = 2048M' >> /usr/local/etc/php/conf.d/docker-php-memlimit.ini;

RUN chmod +x /usr/local/bin/install-php-extensions && install-php-extensions pdo_firebird

RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
RUN composer self-update
RUN composer clear-cache
COPY ../laravel /var/www/laravel
WORKDIR /var/www/laravel/